<div class="modal-block" style="display: none">
</div>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        function getLastProduct(){
            $.ajax({
                url: "http://magent-learn.loc/allproducts/Ajax/GetSuggestProduct",
                type: "GET",
                success: function(data){
                    if(data['answer'] === false){
                        console.log('Empty attribute')
                    }else{
                        const $modalPop = $('.modal-block');
                        $modalPop.css('display', 'block');
                        $modalPop.append("<p> data.answer.data.name </p>")
                        $modalPop.modal('openModal');
                    }
                }
            });
        }

        let options = {
            type: 'popup',
            responsive: true,
            title: 'Suggest another product',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        const popup = modal(options, $('.modal-block'));
        $('#product-addtocart-button').click(function() {
            setTimeout(getLastProduct, 1500);
        });
    });
</script>
