<div class="modal-block" style="display: none">
    <p>Hello) It's modal window.</p>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        let options = {
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        const popup = modal(options, $('.modal-block'));
        $('#product-addtocart-button').click(function() {
            const $modalPop =  $('.modal-block');
            $modalPop.css('display', 'block');
            $modalPop.modal('openModal');
        });
    });
</script>
